guests=["virat", "sachin", "lara", "kallis"]
print("Original list")
print(guests)
print("\n Sorted list")
print(sorted(guests))
print("\n reverse alphabetical order")
print(sorted(guests, reverse=True))
print("Original list")
print(guests)
print("permanently reversed list")
guests.reverse()
print(guests)
print("reversing again to get the originial list")
guests.reverse()
print(guests)
print("sorting the list permanently")
guests.sort()
print(guests)
print("Reverse sorting the list permanently")
guests.sort(reverse=True)
print(guests)
length=len(guests)
print("Here are total number of guests = " +str(len(guests)))
